### ISSUE TITLE
GetWebDriver.ps1 相容性問題

### ISSUE THREAD

**Issue by alicaccs** [Proliantaholic/TaiwanWeatherAQI#3]
1. Windows 10自1803版本起才有內建curl，之前版本（包含2015/2016LTSB長期支援版）無curl可用，無法用其下載WebDriver相關檔案。建議廢棄指定Win10使用curl下載的區段，單純用PowerShell內建功能下載
2. EdgeDriver和GeckoDriver的下載都寫死為64bit，對於尚在使用32bit的用戶（例如某些ATOM平板）無法使用
3. 建議：任何Windows電腦都有內建IE，可以的話還是只使用IEDriver會比較單純？省去用戶選擇瀏覽器的功夫

**Comment by Proliantaholic** [comment]
1. 下次改版會調整.
2. 因時間和設備有限, 並不打算支援32bit, 歡迎您自行修改程式碼.
3. 不用IE的原因:
- 用IEDriver瀏覽網頁資料時無法隱藏視窗, 也就是更新資料時會跳出IE視窗.
- 微軟即將終止支援IE瀏覽器.

**Comment by alicaccs** [comment]
IE是Windows系統元件，依微軟目前規劃來看是自家雲端服務如Azure/Office365等停止支援IE，但沒提過會停止安全性維護這個元件。當然若IEDriver會產生新視窗則造成使用者困擾，不用合理。

32bit部分因我有用到，待不相依curl的版本推出後研究看看，若有成果再送pull request。
